name: mlws
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
dependencies:
  - python=3.10
  # install torch
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - cudatoolkit
  - opencv=4
  - ipykernel=6
  - accelerate # they are 0.17 now
  - xformers
  - av
  - ipywidgets
  - matplotlib
  - pytorch-lightning
  - diffusers
  - transformers
  - scipy
  - safetensors
  - gradio
  - pip
  pip:
    - accelerate==0.17