com.nvidia.cuda = "~11.8"

[com.huggingface]
stabilityai.stable-diffusion-2-depth = "fp16"

[org.pypi]
python = "~3.10"
torch = "^2.1.0"
transformers = "^4.26.1"
diffusers = "^0.14.0"
accelerate = "^0.16.0"
scipy = "^1.10.1"
safetensors = "^0.3.0"
